apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-app
  template:
    metadata:
      labels:
        app: vuln-app
    spec:
      containers:
      - name: vuln-app
        image: vuln-app:latest
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
          runAsUser: 0
